# OpenAI Gym and Python for Q-learning 

In [1]:
!pip install gym
!pip install gymnasium[toy-text]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 70.0 MB/s eta 0:00:00


## Notebook Imports

In [2]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1', render_mode="rgb_array")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Parameters

In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

### Train Q-learning Agent 

In [6]:
rewards_all_episodes = []

# Q-learning Algorithm
for episode in range(num_episodes):
    state = env.reset()[0]
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, truncated, info = env.step(action)
        
        # Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :])) 
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print('*****Average reward per Thousand*****\n')

for r in rewards_per_thousand_episodes:
    print(f'{count}: {sum(r/1000)}')
    count+=1000
    
# Print updated Q-table
print('\n\n*****Q-table*****\n')
print(q_table)

*****Average reward per Thousand*****

1000: 0.03300000000000002
2000: 0.20700000000000016
3000: 0.43200000000000033
4000: 0.5480000000000004
5000: 0.6320000000000005
6000: 0.6710000000000005
7000: 0.6440000000000005
8000: 0.6960000000000005
9000: 0.6900000000000005
10000: 0.6570000000000005


*****Q-table*****

[[0.47778613 0.425566   0.43001875 0.42111357]
 [0.29568785 0.32164248 0.29597377 0.44155516]
 [0.37860636 0.3784898  0.36778446 0.40813978]
 [0.24113848 0.34288069 0.20397167 0.37770481]
 [0.49434174 0.42988984 0.26972071 0.37000059]
 [0.         0.         0.         0.        ]
 [0.17336515 0.16115442 0.32625874 0.07242959]
 [0.         0.         0.         0.        ]
 [0.35547909 0.32256439 0.39230244 0.53078137]
 [0.40245709 0.58059268 0.43547834 0.48330309]
 [0.56481415 0.37512832 0.3652048  0.33431707]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46223395 0.48942854 0.69959648 0.48432051]
 [0.68088383 0.8185724  0.67

### Watch Q-learning Agent Play

In [7]:
for episode in range(3):
    state = env.reset()[0]
    done = False
    print(f'*****EPISODE: {episode+1} *****\n\n\n\n')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1:
                print('****You reached the goal!!!*****')
                time.sleep(3)
                
            else:
                print('****You fell through a hole!****')
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

*****EPISODE: 3 *****




